# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import node_pb2 as node__pb2


class ClientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientLookupReply = channel.unary_unary(
                '/Client/ClientLookupReply',
                request_serializer=node__pb2.LookupReply.SerializeToString,
                response_deserializer=node__pb2.Empty.FromString,
                )
        self.ClientInsertReply = channel.unary_unary(
                '/Client/ClientInsertReply',
                request_serializer=node__pb2.InsertReply.SerializeToString,
                response_deserializer=node__pb2.Empty.FromString,
                )


class ClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientLookupReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientInsertReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientLookupReply': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientLookupReply,
                    request_deserializer=node__pb2.LookupReply.FromString,
                    response_serializer=node__pb2.Empty.SerializeToString,
            ),
            'ClientInsertReply': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientInsertReply,
                    request_deserializer=node__pb2.InsertReply.FromString,
                    response_serializer=node__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Client', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Client(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientLookupReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Client/ClientLookupReply',
            node__pb2.LookupReply.SerializeToString,
            node__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientInsertReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Client/ClientInsertReply',
            node__pb2.InsertReply.SerializeToString,
            node__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
