# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import node_pb2 as node__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63lient.proto\x1a\nnode.proto2b\n\x06\x43lient\x12+\n\x11\x43lientLookupReply\x12\x0c.LookupReply\x1a\x06.Empty\"\x00\x12+\n\x11\x43lientInsertReply\x12\x0c.InsertReply\x1a\x06.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[node__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CLIENT = _descriptor.ServiceDescriptor(
  name='Client',
  full_name='Client',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=28,
  serialized_end=126,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClientLookupReply',
    full_name='Client.ClientLookupReply',
    index=0,
    containing_service=None,
    input_type=node__pb2._LOOKUPREPLY,
    output_type=node__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClientInsertReply',
    full_name='Client.ClientInsertReply',
    index=1,
    containing_service=None,
    input_type=node__pb2._INSERTREPLY,
    output_type=node__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENT)

DESCRIPTOR.services_by_name['Client'] = _CLIENT

# @@protoc_insertion_point(module_scope)
