# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replica.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replica.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rreplica.proto\"\x1a\n\nHatRequest\x12\x0c\n\x04node\x18\x01 \x01(\x05\"-\n\x08HatReply\x12\x0c\n\x04node\x18\x01 \x01(\x05\x12\x13\n\x0bwas_primary\x18\x02 \x01(\x08\",\n\x11UpdateCopyRequest\x12\x0c\n\x04node\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\"\x1f\n\x0fUpdateCopyReply\x12\x0c\n\x04node\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2g\n\x07Replica\x12&\n\nRequestHat\x12\x0b.HatRequest\x1a\t.HatReply\"\x00\x12\x34\n\nUpdateCopy\x12\x12.UpdateCopyRequest\x1a\x10.UpdateCopyReply\"\x00\x62\x06proto3'
)




_HATREQUEST = _descriptor.Descriptor(
  name='HatRequest',
  full_name='HatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='HatRequest.node', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=43,
)


_HATREPLY = _descriptor.Descriptor(
  name='HatReply',
  full_name='HatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='HatReply.node', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='was_primary', full_name='HatReply.was_primary', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=90,
)


_UPDATECOPYREQUEST = _descriptor.Descriptor(
  name='UpdateCopyRequest',
  full_name='UpdateCopyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='UpdateCopyRequest.node', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='UpdateCopyRequest.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=136,
)


_UPDATECOPYREPLY = _descriptor.Descriptor(
  name='UpdateCopyReply',
  full_name='UpdateCopyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='UpdateCopyReply.node', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=169,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['HatRequest'] = _HATREQUEST
DESCRIPTOR.message_types_by_name['HatReply'] = _HATREPLY
DESCRIPTOR.message_types_by_name['UpdateCopyRequest'] = _UPDATECOPYREQUEST
DESCRIPTOR.message_types_by_name['UpdateCopyReply'] = _UPDATECOPYREPLY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HatRequest = _reflection.GeneratedProtocolMessageType('HatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HATREQUEST,
  '__module__' : 'replica_pb2'
  # @@protoc_insertion_point(class_scope:HatRequest)
  })
_sym_db.RegisterMessage(HatRequest)

HatReply = _reflection.GeneratedProtocolMessageType('HatReply', (_message.Message,), {
  'DESCRIPTOR' : _HATREPLY,
  '__module__' : 'replica_pb2'
  # @@protoc_insertion_point(class_scope:HatReply)
  })
_sym_db.RegisterMessage(HatReply)

UpdateCopyRequest = _reflection.GeneratedProtocolMessageType('UpdateCopyRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECOPYREQUEST,
  '__module__' : 'replica_pb2'
  # @@protoc_insertion_point(class_scope:UpdateCopyRequest)
  })
_sym_db.RegisterMessage(UpdateCopyRequest)

UpdateCopyReply = _reflection.GeneratedProtocolMessageType('UpdateCopyReply', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECOPYREPLY,
  '__module__' : 'replica_pb2'
  # @@protoc_insertion_point(class_scope:UpdateCopyReply)
  })
_sym_db.RegisterMessage(UpdateCopyReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'replica_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_REPLICA = _descriptor.ServiceDescriptor(
  name='Replica',
  full_name='Replica',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=180,
  serialized_end=283,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestHat',
    full_name='Replica.RequestHat',
    index=0,
    containing_service=None,
    input_type=_HATREQUEST,
    output_type=_HATREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateCopy',
    full_name='Replica.UpdateCopy',
    index=1,
    containing_service=None,
    input_type=_UPDATECOPYREQUEST,
    output_type=_UPDATECOPYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICA)

DESCRIPTOR.services_by_name['Replica'] = _REPLICA

# @@protoc_insertion_point(module_scope)
