# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import replica_pb2 as replica__pb2


class ReplicaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestHat = channel.unary_unary(
                '/Replica/RequestHat',
                request_serializer=replica__pb2.HatRequest.SerializeToString,
                response_deserializer=replica__pb2.HatReply.FromString,
                )
        self.UpdateCopy = channel.unary_unary(
                '/Replica/UpdateCopy',
                request_serializer=replica__pb2.UpdateCopyRequest.SerializeToString,
                response_deserializer=replica__pb2.UpdateCopyReply.FromString,
                )


class ReplicaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestHat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCopy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestHat': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHat,
                    request_deserializer=replica__pb2.HatRequest.FromString,
                    response_serializer=replica__pb2.HatReply.SerializeToString,
            ),
            'UpdateCopy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCopy,
                    request_deserializer=replica__pb2.UpdateCopyRequest.FromString,
                    response_serializer=replica__pb2.UpdateCopyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Replica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replica(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestHat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Replica/RequestHat',
            replica__pb2.HatRequest.SerializeToString,
            replica__pb2.HatReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCopy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Replica/UpdateCopy',
            replica__pb2.UpdateCopyRequest.SerializeToString,
            replica__pb2.UpdateCopyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
